---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ews-bg-auto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ews-bg-auto
  template:
    metadata:
      labels:
        app: ews-bg-auto
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: api
        image: nginxinc/nginx-unprivileged:alpine
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: "1500m"
            memory: "1000Mi"
          limits:
            cpu: "2500m"
            memory: "1500Mi"
        ports:
          - name: health-check
            containerPort: 5000
            hostPort: 5000
        readinessProbe:
          tcpSocket:
            port: health-check
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: health-check
          initialDelaySeconds: 15
          periodSeconds: 20   
        env:
        - name: TZ
          value: "UTC"          
        envFrom:
        - configMapRef:
            name: ews-bg-auto-configmap