apiVersion: v1
kind: ResourceQuota
metadata:
  name: sm-flexews-quota
  namespace: sm-flexews
spec:
  hard:
    pods: "100"
    services: "50"
    secrets: "100"
    configmaps: "100"
    persistentvolumeclaims: "50"
    requests.cpu: "20"
    requests.memory: "40Gi"
    limits.cpu: "40"
    limits.memory: "80Gi"
    requests.storage: "500Gi"
