# DC1 - Full replicas (Active)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: sm-flexews
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: api
          image: nginxinc/nginx-unprivileged:alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: sm-flexews
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: api
          image: nginxinc/nginx-unprivileged:alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: sm-flexews
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: api
          image: nginxinc/nginx-unprivileged:alpine
